server:
  port: 12000

mybatis-plus:
  mapper-location: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://8.134.156.92:3306/gulimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource